2022-11-06 15:29:19.823 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-06 15:29:19.827 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration climate_template which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-11-06 15:29:20.213 WARNING (MainThread) [homeassistant.components.lovelace] Lovelace is running in storage mode. Define resources via user interface
2022-11-06 15:29:34.036 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Fire' for fully_kiosk integration not ready yet: Cannot connect to host 192.168.86.37:2323 ssl:default [Connect call failed ('192.168.86.37', 2323)]; Retrying in background
2022-11-06 15:29:34.176 ERROR (Thread-2) [tuya_iot] error while get mqtt config
2022-11-06 15:29:34.204 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
    time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'
2022-11-06 15:29:36.869 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{% set max = states('sensor.max_indoor_temperature') | int %} {% set kitchen = states('sensor.2354_kitchen_h_o_sensor_temp') | int %} {% set dining = states('sensor.2354_dining_h_o_sensor_temp') | int %} {% set living = states('sensor.2354_living_h_o_sensor_temp') | int %} {% if (kitchen == max) %}
  Kitchen
{% elif (dining == max) %}
  Dining Room
{% elif (living == max) %}
  Living Room
{% else %}
  Error, no sensor matches max temp
{% endif %}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 420, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1915, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1702, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1394, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'unknown' when rendering template '{% set max = states('sensor.max_indoor_temperature') | int %} {% set kitchen = states('sensor.2354_kitchen_h_o_sensor_temp') | int %} {% set dining = states('sensor.2354_dining_h_o_sensor_temp') | int %} {% set living = states('sensor.2354_living_h_o_sensor_temp') | int %} {% if (kitchen == max) %}
  Kitchen
{% elif (dining == max) %}
  Dining Room
{% elif (living == max) %}
  Living Room
{% else %}
  Error, no sensor matches max temp
{% endif %}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 536, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 422, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'unknown' when rendering template '{% set max = states('sensor.max_indoor_temperature') | int %} {% set kitchen = states('sensor.2354_kitchen_h_o_sensor_temp') | int %} {% set dining = states('sensor.2354_dining_h_o_sensor_temp') | int %} {% set living = states('sensor.2354_living_h_o_sensor_temp') | int %} {% if (kitchen == max) %}
  Kitchen
{% elif (dining == max) %}
  Dining Room
{% elif (living == max) %}
  Living Room
{% else %}
  Error, no sensor matches max temp
{% endif %}' but no default was specified
2022-11-06 15:29:36.880 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: int got invalid input 'unknown' when rendering template '{% set max = states('sensor.max_indoor_temperature') | int %} {% set kitchen = states('sensor.2354_kitchen_h_o_sensor_temp') | int %} {% set dining = states('sensor.2354_dining_h_o_sensor_temp') | int %} {% set living = states('sensor.2354_living_h_o_sensor_temp') | int %} {% if (kitchen == max) %}
  Kitchen
{% elif (dining == max) %}
  Dining Room
{% elif (living == max) %}
  Living Room
{% else %}
  Error, no sensor matches max temp
{% endif %}' but no default was specified') while processing template 'Template("{% set max = states('sensor.max_indoor_temperature') | int %} {% set kitchen = states('sensor.2354_kitchen_h_o_sensor_temp') | int %} {% set dining = states('sensor.2354_dining_h_o_sensor_temp') | int %} {% set living = states('sensor.2354_living_h_o_sensor_temp') | int %} {% if (kitchen == max) %}
  Kitchen
{% elif (dining == max) %}
  Dining Room
{% elif (living == max) %}
  Living Room
{% else %}
  Error, no sensor matches max temp
{% endif %}")' for attribute '_attr_native_value' in entity 'sensor.warmest_space'
2022-11-06 15:33:10.457 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:33:10.471 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2022-11-06 15:34:46.044 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:35:21.275 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:35:26.343 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:35:35.516 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:35:39.733 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:35:42.622 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:36:04.169 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:36:09.266 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:39:06.694 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:40:19.953 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:40:22.418 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:40:24.397 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:40:25.806 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:40:26.305 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:40:31.313 WARNING (MainThread) [homeassistant.helpers.script.climate_controller] climate_controller: Already running
2022-11-06 15:58:42.534 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2022-11-06 16:06:52.526 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /ingress/validate_session request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
2022-11-06 16:06:52.858 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 
2022-11-06 16:06:52.902 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /ingress/session request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
2022-11-06 16:06:52.905 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/session - 
2022-11-06 16:06:57.681 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /ingress/validate_session request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
2022-11-06 16:06:57.684 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 
2022-11-06 16:06:57.687 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /ingress/validate_session request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
2022-11-06 16:06:57.689 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 
2022-11-06 16:06:57.712 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /ingress/session request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
2022-11-06 16:06:57.715 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/session - 
2022-11-06 16:06:57.718 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /ingress/session request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
2022-11-06 16:06:57.720 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/session - 
2022-11-06 16:07:01.540 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - System is not ready with state: setup
2022-11-06 16:07:01.551 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - System is not ready with state: setup
2022-11-06 16:07:01.600 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/session - System is not ready with state: setup
2022-11-06 16:07:01.606 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/session - System is not ready with state: setup
2022-11-06 16:07:52.373 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401
2022-11-06 16:07:52.376 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 
2022-11-06 16:07:57.688 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401
2022-11-06 16:07:57.690 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 
2022-11-06 16:07:57.703 ERROR (MainThread) [homeassistant.components.hassio.handler] /ingress/validate_session return code 401
2022-11-06 16:07:57.705 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/validate_session - 
